### ISSUE TITLE
data for input class net/fabricmc/fabric/impl/client/indigo/renderer/render/ItemRenderContext$VanillaQuadHandler is missing?!

### ISSUE THREAD

**Issue by Juuxel** [Juuxel/LoomQuiltflower#1]

**Comment by comp500** [comment]
Also seems to break accesswidener remapping on an existing dev environment. From my debugging, it seemed to be failing to map as `TinyRemapper.classes` was empty - maybe `finish()` was called too early?

**Comment by Juuxel** [comment]
Still, it doesn't really make sense that LQF causes it - all I do is add a decompiler using Loom's API.

**Comment by Juuxel** [comment]
@comp500 Thanks for pointing me into the direction of Tiny Remapper. It looks like LQF pulled in TR 0.4 into older Loom versions where it didn't work. (just updating to TR 0.4.3 would've probably worked since it has [this fix](https://github.com/FabricMC/tiny-remapper/commit/a38f1d92958678090eba5adf3ad6ca503481c45c), but this way works too)
